name: fabrica
base: core18
version: '0.9'
summary: Build snaps by simply pointing a web form to a git tree
description: |
  Fabrica is a web service to be run on an lxd appliance. It spawns a
  web ui that allows you to point to cloneable git trees, initializes
  lxd and builds snap packages of the provided source trees.

grade: stable
confinement: strict

apps:
  init:
    command: bin/init.py
    daemon: simple
    plugs:
      - lxd
      - mount-observe
      - network-bind
  web:
    command: bin/web
    daemon: simple
    plugs:
      - lxd
      - mount-observe
      - network
      - network-bind
      - system-observe
  watch:
    command: bin/watch
    daemon: simple
    plugs:
      - lxd
      - mount-observe
      - network
      - network-bind
      - system-observe

parts:
  react:
    plugin: nil
    source: .
    override-build: |
      # Install node and npm
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      . "$NVM_DIR/nvm.sh"
      . "$NVM_DIR/bash_completion"

      nvm install lts/*
      nvm run node --version

      cd webapp
      npm install
      npm run build

      mkdir -p $SNAPCRAFT_PART_INSTALL/static/
      cp -r build/static/css $SNAPCRAFT_PART_INSTALL/static/
      cp -r build/static/js $SNAPCRAFT_PART_INSTALL/static/
      cp -r build/static/images $SNAPCRAFT_PART_INSTALL/static/
      cp build/* $SNAPCRAFT_PART_INSTALL/static/ || :
    build-packages:
      - curl
      - python-minimal
      - python-dev


  pylxd:
    plugin: python
    python-packages:
      - pylxd
    build-packages:
      - libffi-dev
      - libssl-dev
  scripts:
    source: .
    plugin: nil
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp bin/init.py $SNAPCRAFT_PART_INSTALL/bin/

  application:
    plugin: go
    source: .
    source-type: git
    build-packages:
      - gcc
    stage-packages:
      - git
      - libcurl4-openssl-dev

  bin:
    source: snap/local
    plugin: dump
    organize:
      "*": /bin/
