name: fabrica
base: core18
version: '0.1'
summary: Build snaps by simply pointing a web form to a git tree
description: |
  Fabrica is a web service to be run on an lxd appliance. It spawns a
  web ui that allows you to point to cloneable git trees, initializes
  lxd and builds snap packages of the provided source trees.

grade: stable
confinement: strict

apps:
  init:
    command: init.py
    daemon: simple
    plugs:
      - lxd
      - mount-observe
      - network-bind
  build:
    command: build.py
    plugs:
      - lxd
      - mount-observe
      - network
      - network-bind
      - system-observe
  ws:
    command: ws.py
    environment:
      PYTHONPATH: $SNAP/lib:$SNAP/usr/lib:$PYTHONPATH
    plugs:
      - lxd
      - home
      - network
      - network-bind
      - system-observe

parts:
  pylxd:
    plugin: python
    python-packages:
      - pylxd
    build-packages:
      - libffi-dev
      - libssl-dev
  scripts:
    source: .
    plugin: nil
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp init.py $SNAPCRAFT_PART_INSTALL/bin/
      cp build.py $SNAPCRAFT_PART_INSTALL/bin/
      cp ws.py $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - python3-websockets
